// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: otp.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const consumeOtpCode = `-- name: ConsumeOtpCode :one
DELETE FROM otp
WHERE code_hash = $1
    AND identifier = $2
    AND expires_at > NOW()
RETURNING id, identifier, code_hash, attempts, expires_at, created_at
`

type ConsumeOtpCodeParams struct {
	CodeHash   string
	Identifier string
}

func (q *Queries) ConsumeOtpCode(ctx context.Context, arg ConsumeOtpCodeParams) (Otp, error) {
	row := q.db.QueryRowContext(ctx, consumeOtpCode, arg.CodeHash, arg.Identifier)
	var i Otp
	err := row.Scan(
		&i.ID,
		&i.Identifier,
		&i.CodeHash,
		&i.Attempts,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const consumeOtpCodeByChallengeID = `-- name: ConsumeOtpCodeByChallengeID :one
DELETE FROM otp
WHERE id = $1
    AND code_hash = $2
    AND expires_at > NOW()
    AND attempts < $3
RETURNING id, identifier, code_hash, attempts, expires_at, created_at
`

type ConsumeOtpCodeByChallengeIDParams struct {
	ID          uuid.UUID
	CodeHash    string
	MaxAttempts int16
}

func (q *Queries) ConsumeOtpCodeByChallengeID(ctx context.Context, arg ConsumeOtpCodeByChallengeIDParams) (Otp, error) {
	row := q.db.QueryRowContext(ctx, consumeOtpCodeByChallengeID, arg.ID, arg.CodeHash, arg.MaxAttempts)
	var i Otp
	err := row.Scan(
		&i.ID,
		&i.Identifier,
		&i.CodeHash,
		&i.Attempts,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const increaseOtpAttempts = `-- name: IncreaseOtpAttempts :exec
UPDATE otp
SET attempts = attempts + 1
WHERE id = $1
    AND expires_at > NOW()
    AND attempts < $2
`

type IncreaseOtpAttemptsParams struct {
	ID          uuid.UUID
	MaxAttempts int16
}

func (q *Queries) IncreaseOtpAttempts(ctx context.Context, arg IncreaseOtpAttemptsParams) error {
	_, err := q.db.ExecContext(ctx, increaseOtpAttempts, arg.ID, arg.MaxAttempts)
	return err
}

const invalidateOtpCodesByIdentifier = `-- name: InvalidateOtpCodesByIdentifier :exec
DELETE FROM otp
WHERE identifier = $1
`

func (q *Queries) InvalidateOtpCodesByIdentifier(ctx context.Context, identifier string) error {
	_, err := q.db.ExecContext(ctx, invalidateOtpCodesByIdentifier, identifier)
	return err
}

const saveOtpCode = `-- name: SaveOtpCode :exec
INSERT INTO otp (
    id, identifier, code_hash, attempts, expires_at, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6
)
`

type SaveOtpCodeParams struct {
	ID         uuid.UUID
	Identifier string
	CodeHash   string
	Attempts   int16
	ExpiresAt  time.Time
	CreatedAt  time.Time
}

func (q *Queries) SaveOtpCode(ctx context.Context, arg SaveOtpCodeParams) error {
	_, err := q.db.ExecContext(ctx, saveOtpCode,
		arg.ID,
		arg.Identifier,
		arg.CodeHash,
		arg.Attempts,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}
