// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: password_reset_tokens.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const consumePasswordResetToken = `-- name: ConsumePasswordResetToken :one
UPDATE password_reset_tokens
SET used_at = NOW()
WHERE token_hash = $1
    AND used_at IS NULL
    AND expires_at > NOW()
RETURNING id, user_id, token_hash, expires_at, used_at, created_at
`

func (q *Queries) ConsumePasswordResetToken(ctx context.Context, tokenHash string) (PasswordResetToken, error) {
	row := q.db.QueryRowContext(ctx, consumePasswordResetToken, tokenHash)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deletePasswordResetTokensByID = `-- name: DeletePasswordResetTokensByID :exec
DELETE FROM password_reset_tokens
WHERE id = $1
`

func (q *Queries) DeletePasswordResetTokensByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePasswordResetTokensByID, id)
	return err
}

const deletePasswordResetTokensByUserID = `-- name: DeletePasswordResetTokensByUserID :exec
DELETE FROM password_reset_tokens
WHERE user_id = $1
`

func (q *Queries) DeletePasswordResetTokensByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePasswordResetTokensByUserID, userID)
	return err
}

const getValidPasswordResetToken = `-- name: GetValidPasswordResetToken :one
SELECT id, user_id, token_hash, expires_at, used_at, created_at
FROM password_reset_tokens
WHERE token_hash = $1
    AND used_at IS NULL
    AND expires_at > NOW()
`

func (q *Queries) GetValidPasswordResetToken(ctx context.Context, tokenHash string) (PasswordResetToken, error) {
	row := q.db.QueryRowContext(ctx, getValidPasswordResetToken, tokenHash)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const savePasswordResetToken = `-- name: SavePasswordResetToken :exec
INSERT INTO password_reset_tokens (
    id, user_id, token_hash, expires_at
) VALUES (
    $1, $2, $3, $4
)
`

type SavePasswordResetTokenParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt time.Time
}

func (q *Queries) SavePasswordResetToken(ctx context.Context, arg SavePasswordResetTokenParams) error {
	_, err := q.db.ExecContext(ctx, savePasswordResetToken,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}
