// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	GetByEmail(ctx context.Context, email string) (User, error)
	SaveUser(ctx context.Context, arg SaveUserParams) error
}

var _ Querier = (*Queries)(nil)
